logging.level.root=WARN
logging.level.io.github.hurelhuyag=DEBUG

spring.application.name=demo-hibernate-sqlite
spring.main.banner-mode=off

spring.threads.virtual.enabled=true

spring.datasource.url = jdbc:sqlite:demo.sqlite
spring.datasource.driverClassName = org.sqlite.JDBC

#spring.datasource.hikari.maximumPoolSize=20
#spring.datasource.hikari.cachePrepStmts=true
#spring.datasource.hikari.prepStmtCacheSize=250
#spring.datasource.hikari.prepStmtCacheSqlLimit=2048

spring.jpa.openInView = false
spring.jpa.showSql = false
spring.jpa.hibernate.ddlAuto = none
spring.jpa.hibernate.naming.physicalStrategy = org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicitStrategy = org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
spring.jpa.properties.hibernate.dialect = org.hibernate.community.dialect.SQLiteDialect

spring.sql.init.data-locations = classpath:/init.sql

spring.native.remove-yaml-support=false
spring.native.remove-jmx-support=false